### ISSUE TITLE
Symfony 3.3.8 requires a change to use environment variables in the config 

### ISSUE THREAD

**Issue by roverwolf** [qandidate-labs/qandidate-toggle-bundle#47]
Symfony 3.3.8 made a change in how it handles environment variables.

Previously (3.3.6) the following configuration worked, but no longer works in 3.3.8.
```
parameters:
    env(FEATURE_1): 'inactive'
    feature_1: '%env(FEATURE_1)%'

qandidate_toggle:
    persistence: config
    toggles:
        feature1:
            name: feature1
            status: '%feature_1%'
```
