### ISSUE TITLE
Cannot use in-set in config

### ISSUE THREAD

**Issue by rimas-kudelis** [qandidate-labs/qandidate-toggle-bundle#66]
I tried configuring my condition to use the `in-set` operator, but could not make it work: if I supply an array to it, like this:
```yaml
            conditions:
                -
                    name: operator-condition
                    key: username
                    operator:
                        name: in-set
                        values: 
                            - 569d6666-25f2-4ff8-9615-1ae4b6a105da
```
then I get an "Expected scalar, but got array" error during configuration merge.
And if I pass a string, like this:
```yaml
            conditions:
                -
                    name: operator-condition
                    key: username
                    operator:
                        name: in-set
                        values: 569d6666-25f2-4ff8-9615-1ae4b6a105da
```
then I get an exception from `InSet::__construct()` about an argument which is supposed to be an array being a string.
